- stat:
    path: "/usr/lib/postgresql/{{ pg_version }}/lib/hypopg.so"
  register: hypopg

- name: download hypopg sources
  unarchive:
    src: "https://github.com/HypoPG/hypopg/archive/{{ powa_hypopg_version }}.tar.gz"
    dest: /tmp
    remote_src: true
  when: hypopg.stat.exists == False

- name: compiling hypopg
  make:
    chdir: "/tmp/hypopg-{{ powa_hypopg_version }}"
  when: hypopg.stat.exists == False

- name: installing hypopg
  become: true
  make:
    chdir: "/tmp/hypopg-{{ powa_hypopg_version }}"
    target: install
  when: hypopg.stat.exists == False

- name: remove sources
  file:
    path: "/tmp/hypopg-{{ powa_hypopg_version }}"
    state: absent
