- name: stats pg_track_settings.so
  stat:
    path: "/usr/lib/postgresql/{{ pg_version }}/lib/pg_track_settings.so"
  register: pg_track_settings

- name: download pg_track_settings sources
  unarchive:
    src: "https://github.com/rjuju/pg_track_settings/archive/{{ pg_track_settings_version }}.tar.gz"
    dest: /tmp
    remote_src: true
  when: not pg_track_settings.stat.exists

- name: compiling pg_track_settings
  make:
    chdir: "/tmp/pg_track_settings-{{ pg_track_settings_version }}"
  when: not pg_track_settings.stat.exists

- name: installing pg_track_settings
  become: true
  make:
    chdir: "/tmp/pg_track_settings-{{ pg_track_settings_version }}"
    target: install
  when: not pg_track_settings.stat.exists

- name: remove sources
  file:
    path: "/tmp/pg_track_settings-{{ pg_track_settings_version }}"
    state: absent
